# Generated by Django 4.1 on 2022-08-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='text',
        ),
        migrations.AddField(
            model_name='station',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
