# Generated by Django 4.1 on 2022-08-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_remove_station_text_station_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Boss',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
    ]
