# Generated by Django 4.1 on 2022-08-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0003_worker_delete_boss_delete_human'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'verbose_name': 'Подстанция', 'verbose_name_plural': 'Подстанции'},
        ),
        migrations.RenameField(
            model_name='worker',
            old_name='Name',
            new_name='name',
        ),
    ]
