# Generated by Django 4.1 on 2022-08-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0004_alter_station_options_rename_name_worker_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AddField(
            model_name='worker',
            name='place_for_work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='station.station'),
        ),
    ]
